---
services:
  postgres:
    image: postgres:latest
    container_name: telecast_recorder_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U telecast_recorder -d telecast_recorder"]
      interval: 5s
      timeout: 5s
      retries: 5
    shm_size: 512m
    restart: always
    environment:
      POSTGRES_USER: telecast_recorder
      POSTGRES_DB: telecast_recorder
      POSTGRES_PASSWORD: telecast_recorder
      POSTGRESQL_LOG_MIN_MESSAGES: warning
    command:
      - "postgres"
      - "-c"
      - "max_wal_size=2GB"
      - "-c"
      - "shared_buffers=512MB"
      - "-c"
      - "checkpoint_timeout=10min"
      - "-c"
      - "checkpoint_completion_target=0.9"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 54327:5432

  redis:
    image: redis:5
    container_name: telecast_recorder_redis
    restart: always
    ports:
      - 6379:6379

volumes:
  postgres_data:
